project:
  type: website

website:
  title: "Emily Lo's Explorations with LLMs"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/emily8354
format:
  html:
    theme: sandstone
    css: styles.css

execute:
  freeze: auto


